# Generated by Django 4.2.1 on 2023-06-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orderhistory', '__first__'),
        ('products', '__first__'),
        ('orderitems', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('password', models.CharField(max_length=100)),
                ('profile_pics', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('newsLetterSub', models.BooleanField(blank=True, default=False, verbose_name='Subscription Status')),
                ('newsLetterEmail', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('cart', models.ManyToManyField(blank=True, related_name='cart', to='orderitems.orderitem')),
                ('orderHistory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='orderhistory.orderhistory')),
                ('wishList', models.ManyToManyField(blank=True, related_name='wishList', to='products.product')),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
