# Generated by Django 4.1.7 on 2023-03-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='products.product'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='wishList',
            field=models.ManyToManyField(blank=True, related_name='wishList', to='products.product'),
        ),
    ]
