# Generated by Django 4.1.7 on 2023-03-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0002_alter_orderitem_options_remove_orderitem_order'),
        ('accounts', '0002_myuser_cart_myuser_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='orderitems.orderitem'),
        ),
    ]
