# Generated by Django 4.1.7 on 2023-03-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0003_alter_orderitem_id'),
        ('accounts', '0006_alter_myuser_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='orderitems.orderitem'),
        ),
    ]
