# Generated by Django 4.1.7 on 2023-03-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_myuser_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='newsLetterAccount',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email Address'),
        ),
    ]
