# Generated by Django 4.1.7 on 2023-03-11 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_myuser_newsletteraccount_alter_myuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='newsLetterAccount',
            new_name='newsLetterEmail',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='newsLetterSub',
            field=models.BooleanField(blank=True, default=False, verbose_name='Subscription Status'),
        ),
    ]
