# Generated by Django 4.1.7 on 2023-03-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0002_alter_orderitem_options_remove_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
