# Generated by Django 4.2.1 on 2023-06-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderhistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name_plural': 'Order History'},
        ),
    ]
