# Generated by Django 4.2.1 on 2023-06-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderItems',
            field=models.ManyToManyField(related_name='orderitems', to='orderitems.orderitem'),
        ),
    ]
