# Generated by Django 4.1.7 on 2023-03-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderitems', '0002_alter_orderitem_options_remove_orderitem_order'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderItems',
            field=models.ManyToManyField(to='orderitems.orderitem'),
        ),
    ]
