# Generated by Django 4.2.1 on 2023-06-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_description_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountedPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
